name: Build Artemis Qt (Linux Only)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        required: true
        default: "develop"

env:
  QT_VERSION: '6.7.0'

jobs:
  build-linux:
    name: Linux Build
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout selected branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}
        submodules: 'recursive'
    
    - name: Setup Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        host: 'linux'
        target: 'desktop'
        modules: 'qtmultimedia'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libegl1-mesa-dev libgl1-mesa-dev libopus-dev libsdl2-dev \
          libsdl2-ttf-dev libssl-dev libavcodec-dev libavformat-dev \
          libswscale-dev libva-dev libvdpau-dev libxkbcommon-dev \
          wayland-protocols libdrm-dev nasm libgbm-dev \
          libfreetype6-dev libasound2-dev libdbus-1-dev \
          libgles2-mesa-dev libglu1-mesa-dev libibus-1.0-dev \
          libpulse-dev libudev-dev libx11-dev libxcursor-dev \
          libxext-dev libxi-dev libxinerama-dev libxrandr-dev \
          libxss-dev libxt-dev libxv-dev libxxf86vm-dev \
          libxcb-dri3-dev libx11-xcb-dev fuse libfuse2

    - name: Install linuxdeployqt
      run: |
        wget -nv https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-7-x86_64.AppImage -O linuxdeployqt.AppImage
        chmod +x linuxdeployqt.AppImage
        sudo mv linuxdeployqt.AppImage /usr/local/bin/linuxdeployqt
    
    - name: Build
      run: |
        export PATH="$Qt6_DIR/bin:$PATH"
        scripts/build-appimage.sh
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artemis-linux
        path: build/installer-release/Moonlight-*-x86_64.AppImage
